exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "Gemfile", "Gemfile.lock"]
safe: true
auto: true
pygments: true

title : Rails Girls Guide -Japanese-
tagline: Site Tagline
author :
  name : Yoko Harada
  email : yokolet@gmail.com
  github : railsgirls-jp
  twitter : username
  feedburner : feedname

production_url : http://railsgirls-jp.github.com

destination: ./_site
lsi:         false
server_port: 4000
markdown:    kramdown
permalink:   pretty
maruku:
  use_tex:    false
  use_divs:   false
  png_dir:    images/latex
  png_url:    /images/latex

comments :
  provider : disqus
  disqus :
    short_name : railsgirls-jp
